/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pompaci;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author mustafa
 */
public class PompaciView extends javax.swing.JFrame {

    private final SqlConnection connection;
    private YakitBilgileri yakit;
    private Client client;
    private Date tarihSaat;

    private Double YakitFiyat;
    private Double ToplamTutar;
    private Double ToplamLitre;
    private boolean dolumBilgisi;
    private String kullaniciAdi;

    /**
     * Creates new form PompaciView
     * @param kullaniciAdi
     */
    public PompaciView(String kullaniciAdi) {
        this.kullaniciAdi = kullaniciAdi;
        connection = new SqlConnection();
        initComponents();
        yakit = new YakitBilgileri();
        updateFiyat();
        updateTarih();
    }

    public void updateTarih() {
        Thread th = new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        tarihSaat = new Date(System.currentTimeMillis());

                        SimpleDateFormat formatter = new SimpleDateFormat("dd.MM.yyyy HH:mm");
                        String tmp = formatter.format(tarihSaat);
                        jTarihSaat.setText(tmp);

                        Thread.sleep(1000);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        });
        th.start();
    }

    public void setFiyatLabel() {
        benzinFiyat.setText(yakit.getFiyat(0).toString() + " TL");
        motorinFiyat.setText(yakit.getFiyat(1).toString() + " TL");
        gazFiyat.setText(yakit.getFiyat(2).toString() + " TL");
    }

    public void updateFiyat() {
        Thread updateFiyat = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    Thread.sleep(1000);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                while (true) {
                    try {
                        benzinFiyat.setText(yakit.getFiyat(0).toString() + " TL");
                        motorinFiyat.setText(yakit.getFiyat(1).toString() + " TL");
                        gazFiyat.setText(yakit.getFiyat(2).toString() + " TL");
                        Thread.sleep(1000);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        });
        updateFiyat.start();
    }

    public void updateYakit() {
        ResultSet rs = connection.executeQuery("select * from Yakit ");
        try {
            while (rs.next()) {
                yakit.setFiyat(rs.getInt(1) - 1, rs.getDouble(4));
                yakit.setStok(rs.getInt(1) - 1, rs.getDouble(3));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        setFiyatLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        litre = new javax.swing.JLabel();
        plakaNo = new javax.swing.JTextField();
        tutar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        benzinFiyat = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        motorinFiyat = new javax.swing.JLabel();
        gazFiyat = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dolumDurumu = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jStokDurumu = new javax.swing.JLabel();
        satisYapButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        pompaNoInput = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        anlikFiyat = new javax.swing.JLabel();
        anlikLitre = new javax.swing.JLabel();
        satisYapButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTarihSaat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Araç Plakası");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        litre.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        litre.setText("--,-- LT");
        getContentPane().add(litre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        plakaNo.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        getContentPane().add(plakaNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 143, -1));

        tutar.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        getContentPane().add(tutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 143, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel4.setText("Tutar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel5.setText("Toplam Litre");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel6.setText("Benzin");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        benzinFiyat.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        benzinFiyat.setText("--.--");
        jPanel1.add(benzinFiyat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 120, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel3.setText("Motorin");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 89, -1));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel7.setText("Gaz");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        motorinFiyat.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        motorinFiyat.setText("--.--");
        jPanel1.add(motorinFiyat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 130, -1));

        gazFiyat.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        gazFiyat.setText("--.--");
        jPanel1.add(gazFiyat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 120, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, 20));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, 20));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 290, 100));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel2.setText("Dolum Durumu:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        dolumDurumu.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        dolumDurumu.setText("-------");
        jPanel2.add(dolumDurumu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel11.setText("Stok Durumu:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        jStokDurumu.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jStokDurumu.setText("-------");
        jPanel2.add(jStokDurumu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 420, 80));

        satisYapButton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        satisYapButton.setText("Satış Yap");
        satisYapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satisYapButton(evt);
            }
        });
        getContentPane().add(satisYapButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 110, 40));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel8.setText("Pompa No");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        pompaNoInput.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        pompaNoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pompaNoInputActionPerformed(evt);
            }
        });
        getContentPane().add(pompaNoInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 143, -1));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel9.setText("Litre:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel13.setText("Fiyat:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        anlikFiyat.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        anlikFiyat.setText("-----------");
        getContentPane().add(anlikFiyat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 210, -1));

        anlikLitre.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        anlikLitre.setText("-----------");
        getContentPane().add(anlikLitre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 200, -1));

        satisYapButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        satisYapButton1.setText("Çıkış Yap");
        satisYapButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisYapButton(evt);
            }
        });
        getContentPane().add(satisYapButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 110, 40));

        jLabel14.setText("Tarih ve Saat :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jTarihSaat.setText("--.--.----   --:--");
        getContentPane().add(jTarihSaat, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public double parseDecimal(String input) throws ParseException {
        NumberFormat numberFormat = NumberFormat.getNumberInstance(Locale.getDefault());
        ParsePosition parsePosition = new ParsePosition(0);
        Number number = numberFormat.parse(input, parsePosition);

        if (parsePosition.getIndex() != input.length()) {
            throw new ParseException("Invalid input", parsePosition.getIndex());
        }

        return number.doubleValue();
    }
    private void satisYapButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satisYapButton
        // TODO add your handling code here:
        // check dolum
        String errorMessage;
        client = new Client();

        if (!jRadioButton1.isSelected() && !jRadioButton2.isSelected() && !jRadioButton3.isSelected()) {
            errorMessage = new String("Yakıt Tipini Seciniz");
            JOptionPane.showMessageDialog(new JFrame(), errorMessage, "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        } else if (pompaNoInput.getText().equals("") || Integer.parseInt(pompaNoInput.getText()) > 6) {
            errorMessage = new String("Pompa Numarasını doğru giriniz");
            JOptionPane.showMessageDialog(new JFrame(), errorMessage, "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        } else if (dolumBilgisi == true) {
            errorMessage = new String("Suanda Dolum Yapılıyor");
            JOptionPane.showMessageDialog(new JFrame(), errorMessage, "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        } else if (plakaNo.getText().equals("")) {
            errorMessage = new String("Plakayı giriniz");
            JOptionPane.showMessageDialog(new JFrame(), errorMessage, "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        } else if (tutar.getText().equals("")) {
            errorMessage = new String("Tutarı giriniz");
            JOptionPane.showMessageDialog(new JFrame(), errorMessage, "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        } else if (!client.isConnected()) {
            errorMessage = new String("Server ile iletişim kurulamıyor");
            JOptionPane.showMessageDialog(new JFrame(), errorMessage, "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            String yakitTuru;
            int id;
            if (jRadioButton1.isSelected()) {
                yakitTuru = "Benzin";
                id = 0;
            } else if (jRadioButton2.isSelected()) {
                yakitTuru = "Motorin";
                id = 1;
            } else {
                yakitTuru = "Gaz";
                id = 2;
            }

            YakitFiyat = yakit.getFiyat(id);
            ToplamTutar = Double.parseDouble(tutar.getText());
            ToplamLitre = ToplamTutar / YakitFiyat;

            ToplamLitre = round4Decimals(ToplamLitre);

            if (ToplamLitre > yakit.getStok(id)) {
                errorMessage = ToplamLitre.toString() + " kadar stok yok. Mevcut Stok: " + yakit.getStok(id);
                JOptionPane.showMessageDialog(new JFrame(), errorMessage, "Dialog",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                litre.setText(ToplamLitre.toString() + " LT");
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        yakitDoldur(ToplamLitre, YakitFiyat, ToplamTutar);
                    }
                }).start();
                String message = pompaNoInput.getText() + "-" + kullaniciAdi + "-" + plakaNo.getText() + "-" + yakitTuru + "-" + ToplamLitre.toString() + "-" + yakit.getFiyat(id) + "-" + tutar.getText() + " TL";
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                String sqlDate = formatter.format(tarihSaat);
                String insert = "INSERT INTO Satis (pompaNo, personelNo, aracPlaka, yakitAdi, yakitFiyati, tutar, litre, zaman) VALUES ('"
                        + Integer.parseInt(pompaNoInput.getText()) + "','"
                        + kullaniciAdi + "','"
                        + plakaNo.getText() + "','"
                        + yakitTuru + "','"
                        + yakit.getFiyat(id) + "','"
                        + Double.parseDouble(tutar.getText()) + "','"
                        + ToplamLitre + "','"
                        + sqlDate + "')";

                Double sonStok = yakit.getStok(id) - ToplamLitre;
                sonStok = round4Decimals(sonStok);
                String update = "UPDATE Yakit set stokMiktari='" + sonStok.toString() + "' where yakitID='" + (id + 1) + "'";
                connection.executeUpdate(update);
                connection.executeUpdate(insert);
                updateYakit();
                jStokDurumu.setText(sonStok.toString() + " LT");
                client.sendMessages(message);
            }
        }
        client.closeConnection();
    }//GEN-LAST:event_satisYapButton

    private void pompaNoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pompaNoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pompaNoInputActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here
        jStokDurumu.setText(yakit.getStok(0).toString() + " LT");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jStokDurumu.setText(yakit.getStok(1).toString() + " LT");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        jStokDurumu.setText(yakit.getStok(2).toString() + " LT");
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void cikisYapButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisYapButton
        // TODO add your handling code here:
        connection.closeConnection();
        System.exit(0);
    }//GEN-LAST:event_cikisYapButton
    double round4Decimals(double d) {
        DecimalFormat twoDForm = new DecimalFormat("#.####");
        return Double.valueOf(twoDForm.format(d));
    }

    public void yakitDoldur(Double toplamLitre, Double yakitFiyat, Double tutar) {
        // 0.2134 200 ms de
        // simdiki + hep >= total ise simdiki = total - .****
        // total 200 ms de 250
        dolumBilgisi = true;
        dolumDurumu.setText("Dolum Yapılıyor");
        Double dolumHizi = 0.2762d;
        Double curr = 0.0000;
        Double anlikFiyatB;

        toplamLitre = round4Decimals(toplamLitre);
        int sleeptime = 100;
        try {
            while (!curr.equals(toplamLitre)) {
                if (curr + dolumHizi >= toplamLitre.intValue() - 1) {
                    dolumHizi = 0.2500d;
                    sleeptime = 200;
                }

                curr += dolumHizi;
                anlikFiyatB = curr * yakitFiyat;
                anlikFiyatB = round4Decimals(anlikFiyatB);
                curr = round4Decimals(curr);

                if (curr.compareTo(toplamLitre) > 0) {
                    curr = toplamLitre;
                    anlikFiyatB = tutar;
                }

                anlikFiyat.setText(anlikFiyatB.toString() + " TL");
                anlikLitre.setText(curr.toString() + " LT");
                Thread.sleep(sleeptime);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        dolumDurumu.setText("Dolum Tamamlandı");
        dolumBilgisi = false;
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anlikFiyat;
    private javax.swing.JLabel anlikLitre;
    private javax.swing.JLabel benzinFiyat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel dolumDurumu;
    private javax.swing.JLabel gazFiyat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JLabel jStokDurumu;
    private javax.swing.JLabel jTarihSaat;
    private javax.swing.JLabel litre;
    private javax.swing.JLabel motorinFiyat;
    private javax.swing.JTextField plakaNo;
    private javax.swing.JTextField pompaNoInput;
    private javax.swing.JButton satisYapButton;
    private javax.swing.JButton satisYapButton1;
    private javax.swing.JTextField tutar;
    // End of variables declaration//GEN-END:variables

}
