/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Otomasyon;

/**
 *
 * @author mustafa
 */
public class Anasayfa extends javax.swing.JFrame {
    private FiyatBilgileri fiyat;
    private YakitBilgileri yakit;
    private PompaTakibi pompa;
    private StokEkle stok;
    private Muhasebe muhasebe;
    /**
     * Creates new form Anasayfa
     * @param server
     */
    public Anasayfa(ServerApp server) {
        initComponents();
        yakit = new YakitBilgileri();
        pompa = new PompaTakibi(this, server);
    }

    Anasayfa() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Pompa Takibi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pompaTakibiMenu(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jButton2.setText("Muhasebe");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muhasebeMenu(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 100, -1));

        jButton3.setText("Stok Takip");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokTakipMenu(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        jButton4.setText("Fiyat Güncelle");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiyatGuncelleMenu(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pompaTakibiMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pompaTakibiMenu
        // TODO add your handling code here:
        this.setVisible(false);
        pompa.setVisible(true);
        
    }//GEN-LAST:event_pompaTakibiMenu

    private void fiyatGuncelleMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiyatGuncelleMenu
        // TODO add your handling code here:
        this.setVisible(false);
        fiyat = new FiyatBilgileri(yakit,this);
        fiyat.setVisible(true);
    }//GEN-LAST:event_fiyatGuncelleMenu

    private void stokTakipMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokTakipMenu
        // TODO add your handling code here:
       setVisible(false);
       stok = new StokEkle(yakit,this);
       stok.setVisible(true);
    }//GEN-LAST:event_stokTakipMenu

    private void muhasebeMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muhasebeMenu
        // TODO add your handling code here:
        setVisible(false);
        muhasebe = new Muhasebe(this);
        muhasebe.setVisible(true);
    }//GEN-LAST:event_muhasebeMenu

    

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables

}
