/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Otomasyon;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mustafa
 */
public class FiyatBilgileri extends javax.swing.JFrame {

    private YakitBilgileri yakitBilgisi;
    private Anasayfa anasayfa;

    /**
     * Creates new form StokTakibi
     *
     * @param yakit
     * @param anasayfa
     */
    public FiyatBilgileri(YakitBilgileri yakit, Anasayfa anasayfa) {
        initComponents();
        this.anasayfa = anasayfa;
        yakitBilgisi = yakit;
        Thread updateFiyat = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    Thread.sleep(1000);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                while (true) {
                    try {
                        benzinFiyat.setText(yakit.getFiyat(0).toString() + " TL");
                        motorinFiyat.setText(yakit.getFiyat(1).toString() + " TL");
                        gazFiyat.setText(yakit.getFiyat(2).toString() + " TL");
                        Thread.sleep(1000);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        });
        updateFiyat.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        benzinFiyat = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        motorinFiyat = new javax.swing.JLabel();
        gazFiyat = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jYakitTipi = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jYeniFiyat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel6.setText("Benzin");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        benzinFiyat.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        benzinFiyat.setText("--.--");
        jPanel1.add(benzinFiyat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 120, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel3.setText("Motorin");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 89, -1));

        motorinFiyat.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        motorinFiyat.setText("--.--");
        jPanel1.add(motorinFiyat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 130, -1));

        gazFiyat.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        gazFiyat.setText("--.--");
        jPanel1.add(gazFiyat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 120, -1));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel8.setText("Gaz");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 290, 100));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel7.setText("Yeni Fiyat");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jYakitTipi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Benzin", "Motorin", "Gaz" }));
        getContentPane().add(jYakitTipi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 110, 30));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel9.setText("Yakıt Tipi");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));
        getContentPane().add(jYeniFiyat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 110, 30));

        jButton1.setText("Stok Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokEkle(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 100, 30));

        jButton2.setText("Ana Menü");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anaMenu(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stokEkle(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokEkle
        // TODO add your handling code here:
        SqlConnection connection = new SqlConnection();
        int yakitTipi = jYakitTipi.getSelectedIndex() + 1;
        Double yeniFiyat = Double.parseDouble(jYeniFiyat.getText());

        if (yakitTipi == 1) {
            benzinFiyat.setText(yeniFiyat.toString() + " TL");
        } else if (yakitTipi == 2) {
            motorinFiyat.setText(yeniFiyat.toString() + " TL");
        } else {
            gazFiyat.setText(yeniFiyat.toString() + " TL");
        }

        connection.executeUpdate("UPDATE Yakit set guncelFiyat='"
                + yeniFiyat + "' where yakitID='"
                + yakitTipi + "'");
        connection.closeConnection();

        yakitBilgisi.setFiyat(yakitTipi - 1, yeniFiyat);
        String warningMessage = "Fiyat Başarıyla Değiştirildi";
        JOptionPane.showMessageDialog(new JFrame(), warningMessage, "Fiyat Bilgisi",
                JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_stokEkle

    private void anaMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anaMenu
        // TODO add your handling code here:
        this.dispose();
        anasayfa.setVisible(true);
    }//GEN-LAST:event_anaMenu

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel benzinFiyat;
    private javax.swing.JLabel gazFiyat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jYakitTipi;
    private javax.swing.JTextField jYeniFiyat;
    private javax.swing.JLabel motorinFiyat;
    // End of variables declaration//GEN-END:variables
}
