/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Otomasyon;

/**
 *
 * @author mustafa
 */
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Muhasebe extends javax.swing.JFrame {

    private final SqlConnection connection;
    /**
     * Creates new form
     */
    private final Anasayfa anasayfa;

    public Muhasebe(Anasayfa anasayfa) {
        initComponents();
        this.anasayfa = anasayfa;
        connection = new SqlConnection();
        satisDegerleri();
    }

    public void satisDegerleri() {
        Date bugun = new Date(System.currentTimeMillis());
        Date gecenHafta = new Date(System.currentTimeMillis() - 24 * 60 * 60 * 1000 * 7);
        Date yarin = new Date(System.currentTimeMillis() + 24 * 60 * 60 * 1000);
        Date gecenAy = new Date(System.currentTimeMillis() - 24 * 60 * 60 * 1000 * 21 - 24 * 60 * 60 * 1000 * 9);
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");

        ResultSet[] rs = new ResultSet[3];

        rs[0] = connection.executeQuery("select tutar from Satis where zaman >='" + formatter.format(bugun) + "' and zaman <='" + formatter.format(yarin) + "'");
        rs[1] = connection.executeQuery("select tutar from Satis where zaman >='" + formatter.format(gecenHafta) + "' and zaman <='" + formatter.format(yarin) + "'");
        rs[2] = connection.executeQuery("select tutar from Satis where zaman >='" + formatter.format(gecenAy) + "' and zaman <='" + formatter.format(yarin) + "'");

        try {
            int i = 0;
            while (i < 3) {
                Double d = 0.0000d;
                while (rs[i].next()) {
                    d += rs[i].getDouble(1);
                }
                if (i == 0) {
                    jGunlukSatis.setText(d.toString() + " TL");
                } else if (i == 1) {
                    jHaftalikSatis.setText(d.toString() + " TL");
                } else {
                    jAylikSatis.setText(d.toString() + " TL");
                }
                i++;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void queryTable(String query) {

        try {
            ResultSet rs = connection.executeQuery(query);

            List<List<String>> data = new ArrayList<List<String>>();

            while (rs.next()) {
                ArrayList<String> s = new ArrayList<>();
                for (int i = 1; i < 10; i++) {
                    s.add(rs.getString(i));
                }
                data.add(s);
            }
            updateTable(data);
            Thread.sleep(10000);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void updateTable(List<List<String>> data) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);
        for (int i = 0; i < data.size(); i++) {
            model.addRow(new Object[]{
                data.get(i).get(0),//0
                data.get(i).get(2),//1
                data.get(i).get(3),//2
                data.get(i).get(1),//3
                data.get(i).get(4),//4
                data.get(i).get(5),//5
                data.get(i).get(7),//6
                data.get(i).get(6),//7
                data.get(i).get(8)});//8
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPompaSatis = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jGunlukSatis = new javax.swing.JLabel();
        jAylikSatis = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jHaftalikSatis = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPersonelNo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPompaNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPersonelSatis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Satış ID", "Pompa No", "Personel No", "Araç Plakası", "Yakıt Adı", "Yakıt Fiyatı", "Litre", "Toplam Tutar", "Zaman"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(3);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(3);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(3);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(3);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(3);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(3);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(3);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(100);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 990, 175));

        jPompaSatis.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jPompaSatis.setText("--.-- TL");
        getContentPane().add(jPompaSatis, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 90, -1, 30));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel2.setText("Aylık Satış Tutarı :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jGunlukSatis.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jGunlukSatis.setText("--.-- TL");
        getContentPane().add(jGunlukSatis, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 150, 30));

        jAylikSatis.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jAylikSatis.setText("--.-- TL");
        getContentPane().add(jAylikSatis, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 150, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel5.setText("Haftalık Satış Tutarı :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jHaftalikSatis.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jHaftalikSatis.setText("--.-- TL");
        getContentPane().add(jHaftalikSatis, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 140, 30));

        jButton1.setText("Ana Sayfa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anasayfaMenu(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton2.setText("Tüm Satışları Listele");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tumSatisListele(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jButton3.setText("Pompa Numarasına Göre Listele");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pompaNoGoreListele(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        jButton4.setText("Personele Göre Listele");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personeleGoreListele(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel7.setText("Günlük Satış Tutarı :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        getContentPane().add(jPersonelNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 100, 30));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel8.setText("Pompa Günlük Satış :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, -1, 30));
        getContentPane().add(jPompaNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 100, 30));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel9.setText("Personel No :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, 30));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel10.setText("Pompa No :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, 30));

        jButton6.setText("Yenile");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekranYenile(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel3.setText("Personel Günlük Satış :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, -1, 30));

        jPersonelSatis.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jPersonelSatis.setText("--.-- TL");
        getContentPane().add(jPersonelSatis, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anasayfaMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anasayfaMenu
        // TODO add your handling code here:
        this.dispose();
        anasayfa.setVisible(true);

    }//GEN-LAST:event_anasayfaMenu

    private void tumSatisListele(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tumSatisListele
        // TODO add your handling code here:
        queryTable("select * from Satis");
    }//GEN-LAST:event_tumSatisListele

    private void pompaNoGoreListele(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pompaNoGoreListele
        // TODO add your handling code here:
        if (jPompaNo.getText().compareTo("1") == 0
                || jPompaNo.getText().compareTo("2") == 0
                || jPompaNo.getText().compareTo("3") == 0
                || jPompaNo.getText().compareTo("4") == 0
                || jPompaNo.getText().compareTo("5") == 0
                || jPompaNo.getText().compareTo("6") == 0) {
            ResultSet rs = connection.executeQuery("select tutar from Satis where pompaNo='" + jPompaNo.getText() + "'");

            try {
                Double toplam = 0.00d;
                while (rs.next()) {
                    toplam += rs.getDouble(1);
                }
                jPompaSatis.setText(toplam.toString() + " TL");
            } catch (Exception e) {
                e.printStackTrace();
            }

            queryTable("select * from Satis where pompaNo='" + jPompaNo.getText() + "'");
        } else {
            String errorMessage = "Pompa Numarasını Doğru Giriniz";
            JOptionPane.showMessageDialog(new JFrame(), errorMessage, "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_pompaNoGoreListele

    private void personeleGoreListele(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personeleGoreListele
        // TODO add your handling code here:
        ResultSet rs = connection.executeQuery("SELECT personelNo FROM Personel");
        List<String> user = new ArrayList<>();
        try {
            while (rs.next()) {
                user.add(rs.getString(1));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        if (user.contains(jPersonelNo.getText())) {
            rs = connection.executeQuery("select tutar from Satis where personelNo='" + jPersonelNo.getText() + "'");

            try {
                Double toplam = 0.00d;
                while (rs.next()) {
                    toplam += rs.getDouble(1);
                }
                jPersonelSatis.setText(toplam.toString() + " TL");
            } catch (Exception e) {
                e.printStackTrace();
            }

            queryTable("select * from Satis where personelNo='" + jPersonelNo.getText() + "'");
        } else {
            String errorMessage = "Personel Numarasını Doğru Giriniz";
            JOptionPane.showMessageDialog(new JFrame(), errorMessage, "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_personeleGoreListele

    private void ekranYenile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekranYenile
        // TODO add your handling code here:
        satisDegerleri();
    }//GEN-LAST:event_ekranYenile

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAylikSatis;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jGunlukSatis;
    private javax.swing.JLabel jHaftalikSatis;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jPersonelNo;
    private javax.swing.JLabel jPersonelSatis;
    private javax.swing.JTextField jPompaNo;
    private javax.swing.JLabel jPompaSatis;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
