/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Otomasyon;

import java.text.DecimalFormat;

/**
 *
 * @author mustafa
 */
public class PompaView extends javax.swing.JPanel {

    /**
     * Creates new form Pompa
     */
    public PompaView() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pompaNo = new javax.swing.JLabel();
        toplamTutar = new javax.swing.JLabel();
        pompaci = new javax.swing.JLabel();
        fiyat = new javax.swing.JLabel();
        litre = new javax.swing.JLabel();
        plakaNo = new javax.swing.JLabel();
        yakitTipi = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        anlikLitre = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        anlikFiyat = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tarih = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pompaNo.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        pompaNo.setText("1");
        add(pompaNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 23, 40, -1));

        toplamTutar.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        toplamTutar.setText("---------");
        add(toplamTutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, 40));

        pompaci.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        pompaci.setText("---------");
        add(pompaci, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        fiyat.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        fiyat.setText("---------");
        add(fiyat, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 190, -1));

        litre.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        litre.setText("---------");
        add(litre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        plakaNo.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        plakaNo.setText("---------");
        add(plakaNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        yakitTipi.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        yakitTipi.setText("---------");
        add(yakitTipi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jLabel3.setText("Fiyat");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jLabel4.setText("Litre");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        jLabel5.setText("Araç Plakası");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        jLabel7.setText("Toplam Tutar");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        jLabel8.setText("Anlık Tutar");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        anlikLitre.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        anlikLitre.setText("---------");
        add(anlikLitre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel9.setText("Doldurulan Litre");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        anlikFiyat.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        anlikFiyat.setText("---------");
        add(anlikFiyat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, 40));

        jLabel6.setText("Personel");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel10.setText("Yakıt Tipi");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel2.setText("Tarih :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        tarih.setText("--.--.----");
        add(tarih, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 180, -1));
    }// </editor-fold>//GEN-END:initComponents

    double round4Decimals(double d) {
        DecimalFormat twoDForm = new DecimalFormat("#.####");
        return Double.valueOf(twoDForm.format(d));
    }

    public void yakitDoldur(Double toplamLitre, Double yakitFiyat, Double tutar) {
        //0.2134 200 ms de
        // simdiki + hep >= total ise simdiki = total - 1
        // total 200 ms de 250
        Double dolumHizi = 0.2762d;
        Double curr = 0.0000d;
        Double anlikFiyatB;
        toplamLitre = round4Decimals(toplamLitre);
        int sleeptime = 100;
        try {
            while (!curr.equals(toplamLitre)) {
                if (curr + dolumHizi >= toplamLitre.intValue() - 1) {
                    dolumHizi = 0.2500d;
                    sleeptime = 200;
                }
                
                curr += dolumHizi;
                anlikFiyatB = curr * yakitFiyat;
                anlikFiyatB = round4Decimals(anlikFiyatB);
                curr = round4Decimals(curr);
                
                if (curr.compareTo(toplamLitre) > 0) {
                    curr = toplamLitre;
                    anlikFiyatB = tutar;   
                }

                anlikFiyat.setText(anlikFiyatB.toString() + " TL");
                anlikLitre.setText(curr.toString() + " LT");
                Thread.sleep(sleeptime);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel anlikFiyat;
    public javax.swing.JLabel anlikLitre;
    public javax.swing.JLabel fiyat;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel litre;
    public javax.swing.JLabel plakaNo;
    public javax.swing.JLabel pompaNo;
    public javax.swing.JLabel pompaci;
    public javax.swing.JLabel tarih;
    public javax.swing.JLabel toplamTutar;
    public javax.swing.JLabel yakitTipi;
    // End of variables declaration//GEN-END:variables

}
