/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Otomasyon;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mustafa
 */
public class StokEkle extends javax.swing.JFrame {

    private final YakitBilgileri yakitBilgisi;
    private final Anasayfa anasayfa;

    /**
     * Creates new form StokTakibi
     *
     * @param yakit
     * @param anasayfa
     */
    public StokEkle(YakitBilgileri yakit, Anasayfa anasayfa) {
        initComponents();
        this.anasayfa = anasayfa;
        yakitBilgisi = yakit;
        Thread updateStok = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    Thread.sleep(1000);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                while (true) {

                    try {
                        benzinStok.setText(yakit.getStok(0).toString() + " LT");
                        motorinStok.setText(yakit.getStok(1).toString() + " LT");
                        gazStok.setText(yakit.getStok(2).toString() + " LT");
                        Thread.sleep(1000);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        });
        updateStok.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        benzinStok = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        motorinStok = new javax.swing.JLabel();
        gazStok = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jYakitTipi = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jEklenecekStok = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel6.setText("Benzin");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        benzinStok.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        benzinStok.setText("--.--");
        jPanel1.add(benzinStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 120, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel3.setText("Motorin");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 89, -1));

        motorinStok.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        motorinStok.setText("--.--");
        jPanel1.add(motorinStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 130, -1));

        gazStok.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        gazStok.setText("--.--");
        jPanel1.add(gazStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 120, -1));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel8.setText("Gaz");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 290, 100));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel7.setText("Eklenecek LT");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jYakitTipi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Benzin", "Motorin", "Gaz" }));
        getContentPane().add(jYakitTipi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 110, 30));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel9.setText("Yakıt Tipi");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));
        getContentPane().add(jEklenecekStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 110, 30));

        jButton1.setText("Stok Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokEkle(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 100, 30));

        jButton2.setText("Anasayfa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anasayfaMenu(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stokEkle(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokEkle
        // TODO add your handling code here:
        SqlConnection connection = new SqlConnection();
        int yakitTipi = jYakitTipi.getSelectedIndex() + 1;
        Double eklenecekStok = Double.parseDouble(jEklenecekStok.getText());
        Double yeniStok = yakitBilgisi.getStok(yakitTipi - 1) + eklenecekStok;

        if (yakitTipi == 1) {
            benzinStok.setText(yeniStok.toString() + " LT");
        } else if (yakitTipi == 2) {
            motorinStok.setText(yeniStok.toString() + " LT");
        } else {
            gazStok.setText(yeniStok.toString() + " LT");
        }

        connection.executeUpdate("UPDATE Yakit set stokMiktari='"
                + yeniStok + "' where yakitID='"
                + yakitTipi + "'");
        connection.closeConnection();

        yakitBilgisi.setStok(yakitTipi - 1, yeniStok);
        String warningMessage = "Stok Başarıyla Eklendi";
        JOptionPane.showMessageDialog(new JFrame(), warningMessage, "Stok Bilgisi",
                JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_stokEkle

    private void anasayfaMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anasayfaMenu
        // TODO add your handling code here:
        this.dispose();
        anasayfa.setVisible(true);
    }//GEN-LAST:event_anasayfaMenu

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel benzinStok;
    private javax.swing.JLabel gazStok;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jEklenecekStok;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jYakitTipi;
    private javax.swing.JLabel motorinStok;
    // End of variables declaration//GEN-END:variables
}
